# Generated by Django 3.0.4 on 2020-05-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20200529_1758'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blockchain',
            table='Blockchain',
        ),
    ]
