# Generated by Django 3.0.4 on 2020-07-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_register_access_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_access_codes',
            name='email',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='email'),
        ),
    ]
