# Generated by Django 3.0.4 on 2020-05-17 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=36)),
                ('last_name', models.CharField(max_length=36)),
                ('primary_phone', models.CharField(max_length=10)),
                ('cell_phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Demographics',
            fields=[
                ('Patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EHR_System.Patient')),
                ('ethnicity', models.CharField(blank=True, max_length=36)),
                ('race', models.CharField(blank=True, max_length=36)),
                ('gender', models.CharField(blank=True, max_length=36)),
                ('sex', models.CharField(max_length=36)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(default=0)),
                ('body_mass_index', models.DecimalField(decimal_places=3, max_digits=6)),
                ('primary_language', models.CharField(blank=True, max_length=36)),
                ('hair_color', models.CharField(blank=True, max_length=36)),
                ('eye_color', models.CharField(blank=True, max_length=36)),
                ('dominant_hand', models.CharField(blank=True, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency_Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=36)),
                ('last_name', models.CharField(max_length=36)),
                ('primary_phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship_to_patient', models.CharField(max_length=26)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHR_System.Patient')),
            ],
        ),
    ]
