# Generated by Django 3.0.4 on 2020-05-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EHR_System', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_demographics',
            old_name='Patient',
            new_name='patient',
        ),
    ]
