# Generated by Django 3.0.4 on 2020-05-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EHR_System', '0002_auto_20200517_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=75)),
                ('frequency_description', models.CharField(max_length=120)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHR_System.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergic_to', models.CharField(max_length=50)),
                ('allergy_notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHR_System.Patient')),
            ],
        ),
    ]
