# Generated by Django 3.0.4 on 2020-05-17 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EHR_System', '0003_allergies_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergies',
            name='allergy_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Surgical_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('operating_doctors', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('notes', models.TextField()),
                ('outcome', models.TextField()),
                ('complications', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHR_System.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=120)),
                ('main_complaint', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('type_of_visit', models.CharField(max_length=75)),
                ('examining_doctor', models.CharField(max_length=75)),
                ('date_time', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHR_System.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Immunizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('complications', models.TextField(blank=True, default='No Complications')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHR_System.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='History_Of_Transfusions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('units', models.DecimalField(decimal_places=3, max_digits=6)),
                ('type_of_transfusion', models.CharField(max_length=75)),
                ('veinous_access_device', models.CharField(blank=True, max_length=75)),
                ('infusion_device', models.CharField(blank=True, max_length=75)),
                ('infusion_device_settings', models.TextField(blank=True)),
                ('blood_type', models.CharField(max_length=3)),
                ('complications', models.TextField(blank=True, default='No Complications')),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHR_System.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='History_Of_Present_Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset', models.DateTimeField()),
                ('illness', models.CharField(max_length=75)),
                ('body_location', models.CharField(max_length=135)),
                ('description', models.TextField(blank=True)),
                ('aggravating_factors', models.TextField(blank=True)),
                ('alleviating_factors', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHR_System.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Family_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_first_name', models.CharField(max_length=36)),
                ('family_last_name', models.CharField(max_length=36)),
                ('relationship_to_patient', models.CharField(max_length=26)),
                ('health_status', models.CharField(blank=True, max_length=75)),
                ('date_of_birth', models.DateField(blank=True)),
                ('date_of_death', models.DateField(blank=True)),
                ('cause_of_death', models.TextField(blank=True)),
                ('description_of_illnesses', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHR_System.Patient')),
            ],
        ),
    ]
