# Generated by Django 3.0.4 on 2020-05-17 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EHR_System', '0004_auto_20200517_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phys_Exam_Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmi', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('r_carotid_pulses_desc', models.CharField(blank=True, max_length=200)),
                ('l_carotid_pulses_desc', models.CharField(blank=True, max_length=200)),
                ('r_brachial_pulses_desc', models.CharField(blank=True, max_length=200)),
                ('l_brachial_pulses_desc', models.CharField(blank=True, max_length=200)),
                ('r_radial_pulses_desc', models.CharField(blank=True, max_length=200)),
                ('l_radial_pulses_desc', models.CharField(blank=True, max_length=200)),
                ('r_femoral_pulses_desc', models.CharField(blank=True, max_length=200)),
                ('l_femoral_pulses_desc', models.CharField(blank=True, max_length=200)),
                ('r_dorsalis_pedis_pulses_desc', models.CharField(blank=True, max_length=200)),
                ('l_dorsalis_pedis_pulses_desc', models.CharField(blank=True, max_length=200)),
                ('r_posterior_tibial_pulses_desc', models.CharField(blank=True, max_length=200)),
                ('l_posterior_tibial_pulses_desc', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Phys_Exam_Vitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure_right_palpatation', models.CharField(blank=True, max_length=12)),
                ('pressure_left_palpatation', models.CharField(blank=True, max_length=12)),
                ('pressure_right_auscultation', models.CharField(blank=True, max_length=12)),
                ('pressure_left_auscultation', models.CharField(blank=True, max_length=12)),
                ('heart_rate', models.IntegerField(null=True)),
                ('respiration_rate', models.IntegerField(null=True)),
                ('temperature_celcius', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Phys_Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('examining_doctor', models.CharField(max_length=75)),
                ('weight_lbs', models.DecimalField(decimal_places=3, max_digits=7)),
                ('physique', models.CharField(blank=True, max_length=200)),
                ('lymph_nodes_desc', models.TextField(blank=True)),
                ('chest_desc', models.TextField(blank=True)),
                ('abdomen_desc', models.TextField(blank=True)),
                ('extremities_desc', models.TextField(blank=True)),
                ('neurological_desc', models.TextField(blank=True)),
                ('pelvic_desc', models.TextField(blank=True)),
                ('genitalia_desc', models.TextField(blank=True)),
                ('rectal_desc', models.TextField(blank=True)),
                ('formulation', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('heart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='EHR_System.Phys_Exam_Heart')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHR_System.Patient')),
                ('vitals', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='EHR_System.Phys_Exam_Vitals')),
            ],
        ),
        migrations.CreateModel(
            name='History_Of_Illnesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset_date', models.DateTimeField()),
                ('date_cured', models.DateTimeField(blank=True, null=True)),
                ('illness', models.CharField(max_length=75)),
                ('body_location', models.CharField(max_length=135)),
                ('description', models.TextField(blank=True)),
                ('aggravating_factors', models.TextField(blank=True)),
                ('alleviating_factors', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHR_System.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Disabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset_date', models.DateTimeField()),
                ('disability', models.CharField(max_length=75)),
                ('description', models.TextField(blank=True)),
                ('aggravating_factors', models.TextField(blank=True)),
                ('alleviating_factors', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EHR_System.Patient')),
            ],
        ),
    ]
