# Generated by Django 3.0.4 on 2020-05-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHR_System', '0005_disabilities_history_of_illnesses_phys_exam_phys_exam_heart_phys_exam_vitals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phys_exam',
            name='physique',
        ),
        migrations.AddField(
            model_name='phys_exam',
            name='height_in',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient_demographics',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient_demographics',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='phys_exam',
            name='weight_lbs',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
