# Generated by Django 3.0.4 on 2020-05-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EHR_System', '0006_auto_20200520_0129'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='phys_exam',
            table='Phys_Exam',
        ),
    ]
