# Generated by Django 3.0.4 on 2020-05-20 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EHR_System', '0007_auto_20200520_0137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient_demographics',
            table='Patient_Demographics',
        ),
    ]
