# Generated by Django 3.0.4 on 2020-05-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EHR_System', '0009_auto_20200520_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_demographics',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_demographics', serialize=False, to='EHR_System.Patient'),
        ),
    ]
