# Generated by Django 3.0.4 on 2020-05-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHR_System', '0012_auto_20200522_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cell_phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='patient',
            name='primary_phone',
            field=models.CharField(max_length=13),
        ),
    ]
