# Generated by Django 3.0.4 on 2020-05-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHR_System', '0014_auto_20200525_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_of_transfusions',
            name='reason',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
