# Generated by Django 3.0.4 on 2020-07-09 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EHR_System', '0015_history_of_transfusions_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='authorized_viewers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
